#!/usr/bin/perl -w

use 5.014;			# perl -we 'use 5.014; print "z"x5.1."\n";'
use utf8;			# perl -We 'use 5.014; my $x="z"x5.1 ;print $x."\n";'
				# perl -e 'use utf8; print chr(25340)."\n";'
				# perl -e 'use utf8; print ord("拼")."\n";'
				# perldoc Term::ReadLine
				# perldoc -m Math::Complex
				# perldoc|info|man perldoc|perltoc|perlintro|perlvar|perlstyle|perlop
				# perldoc -f chomp
use Math::BigFloat;		# cpan Math::BigFloat
say "Input the radius of a circle for compute its circumference...";
chomp(my $radius = <STDIN>);
my $π = Math::BigFloat->bpi(3);     # PI to 100 digits
my $circle_circumference = 2 * $π * $radius;  # 0x03C0 -- GREEK SMALL LETTER PI: π
					      # Text Entry Settings > Greek(extended) > keyboard ICON(bottom-right corner)
					      # Keyboard Layout Chart
					      #x 2 * $pi * chomp($radius)
					      #x $radius = chomp($radius)
if ($radius < 0) {			      #x 2**3
    $circle_circumference = 0;
    say 'Your radius is less than '."\Uzero\E, so the circumference of the circle with a radius of $radius is $circle_circumference :)";
} else {
    say 'Hi, the circumference of the circle with a radius of '.$radius." is $circle_circumference in \Uprecision\E 3.";
}
